import { createReadStream, existsSync } from "node:fs";
import * as Path from "node:path";
import { createInterface } from "node:readline";
import { createGunzip } from "node:zlib";

import type {
  CleanupAnalysis,
  CleanupSettings,
  CleanupSuggestion,
  DirectoryHotspot,
  ScanFileRecord,
  SuggestionCategory,
  SuggestionRisk,
} from "./contracts";
import { attachPipeErrorHandlers } from "./streamSafety";

let nextId = 0;
const uid = () => `sug-${++nextId}-${Date.now()}`;

const TEMP_EXTENSIONS = new Set([".tmp", ".temp", ".bak", ".swp", ".swo", ".old", ".orig"]);
const LOG_EXTENSIONS = new Set([".log", ".log1", ".log2", ".etl"]);
const INSTALLER_EXTENSIONS = new Set([".msi", ".msix", ".exe", ".appx", ".dmg", ".pkg"]);
const LARGE_MEDIA_EXTENSIONS = new Set([
  ".avi", ".mkv", ".mov", ".mp4", ".wmv", ".m4v", ".webm",
  ".iso", ".img", ".vhd", ".vhdx", ".vmdk",
]);

const BUILD_CACHE_DIRS = new Set([
  "node_modules", ".next", "dist", "build", "target", "out",
  ".parcel-cache", ".turbo", ".cache", ".yarn", ".pnpm-store",
  "coverage", "__pycache__", ".tox", ".mypy_cache", ".pytest_cache",
  "obj", "bin", "Debug", "Release", "x64", "x86",
  ".gradle", ".m2", ".ivy2",
]);

const BROWSER_CACHE_PATHS = [
  "AppData/Local/Google/Chrome/User Data/Default/Cache",
  "AppData/Local/Microsoft/Edge/User Data/Default/Cache",
  "AppData/Local/Mozilla/Firefox/Profiles",
  "AppData/Local/BraveSoftware/Brave-Browser/User Data/Default/Cache",
];

const SYSTEM_TEMP_PATHS = [
  "AppData/Local/Temp",
  "Windows/Temp",
  "AppData/Local/CrashDumps",
];

const ONE_DAY_MS = 24 * 60 * 60 * 1000;

export function analyzeForCleanup(
  rootPath: string,
  files: ScanFileRecord[],
  directories: DirectoryHotspot[],
  settings: CleanupSettings,
): CleanupAnalysis {
  const suggestions: CleanupSuggestion[] = [];
  const now = Date.now();
  const oldThresholdMs = settings.oldFileThresholdDays * ONE_DAY_MS;

  // Group files by category
  if (settings.autoDetectTempFiles) {
    const tempFiles = files.filter(
      (f) => TEMP_EXTENSIONS.has(f.extension) || matchesTempPath(f.path),
    );
    if (tempFiles.length > 0) {
      suggestions.push(buildSuggestion("temp-files", "safe", "Temporary Files", tempFiles,
        "Temporary files created by applications and the OS. Safe to remove."));
    }

    const logFiles = files.filter((f) => LOG_EXTENSIONS.has(f.extension));
    if (logFiles.length > 0) {
      suggestions.push(buildSuggestion("logs", "low", "Log Files", logFiles,
        "Application and system log files. Usually safe to remove, but check if you need them for debugging."));
    }
  }

  if (settings.autoDetectCaches) {
    const cacheDirs = directories.filter((d) => {
      const dirName = Path.basename(d.path);
      return BUILD_CACHE_DIRS.has(dirName);
    });
    if (cacheDirs.length > 0) {
      suggestions.push(buildDirSuggestion("build-cache", "low", "Build & Package Caches", cacheDirs,
        "Build outputs and package manager caches. Can be regenerated by rebuilding the project."));
    }

    const browserCacheDirs = directories.filter((d) =>
      BROWSER_CACHE_PATHS.some((bp) => normalizePath(d.path).includes(normalizePath(bp))),
    );
    if (browserCacheDirs.length > 0) {
      suggestions.push(buildDirSuggestion("browser-cache", "low", "Browser Caches", browserCacheDirs,
        "Web browser cache files. Browsers will rebuild these automatically."));
    }

    const systemTempDirs = directories.filter((d) =>
      SYSTEM_TEMP_PATHS.some((sp) => normalizePath(d.path).includes(normalizePath(sp))),
    );
    if (systemTempDirs.length > 0) {
      suggestions.push(buildDirSuggestion("system-cache", "low", "System Temp & Crash Dumps", systemTempDirs,
        "System temporary files and crash dumps. Usually safe to clean."));
    }
  }

  if (settings.autoDetectOldDownloads) {
    const oldFiles = files.filter(
      (f) => now - f.modifiedAt > oldThresholdMs,
    );
    const oldInstallers = oldFiles.filter((f) => INSTALLER_EXTENSIONS.has(f.extension));
    if (oldInstallers.length > 0) {
      suggestions.push(buildSuggestion("installer-leftovers", "low",
        `Old Installers (>${settings.oldFileThresholdDays}d)`, oldInstallers,
        "Installer files that haven't been modified in a long time. You've likely already installed these."));
    }

    const oldDownloads = oldFiles.filter(
      (f) => f.path.toLowerCase().includes("download") && !INSTALLER_EXTENSIONS.has(f.extension),
    );
    if (oldDownloads.length > 0) {
      suggestions.push(buildSuggestion("old-downloads", "medium",
        `Old Downloads (>${settings.oldFileThresholdDays}d)`, oldDownloads,
        "Files in download folders that haven't been touched in a while. Review before deleting."));
    }
  }

  // Large media files (always surface these)
  const largeMedia = files.filter(
    (f) => LARGE_MEDIA_EXTENSIONS.has(f.extension) && f.size > 100 * 1024 * 1024,
  );
  if (largeMedia.length > 0) {
    suggestions.push(buildSuggestion("large-media", "medium", "Large Media & Disk Images", largeMedia,
      "Large video files and disk images. Check if you still need these — they're often the biggest space hogs."));
  }

  // Sort by total reclaimable size (biggest wins first)
  suggestions.sort((a, b) => b.totalSize - a.totalSize);

  return {
    suggestions,
    totalReclaimableBytes: suggestions.reduce((sum, s) => sum + s.totalSize, 0),
    analyzedAt: now,
    scanRootPath: rootPath,
  };
}

function buildSuggestion(
  category: SuggestionCategory,
  risk: SuggestionRisk,
  title: string,
  files: ScanFileRecord[],
  reasoning: string,
): CleanupSuggestion {
  return {
    id: uid(),
    category,
    risk,
    title,
    description: `${files.length} file${files.length === 1 ? "" : "s"}, ${formatBytes(totalSize(files))}`,
    paths: files.map((f) => f.path),
    totalSize: totalSize(files),
    fileCount: files.length,
    reasoning,
  };
}

function buildDirSuggestion(
  category: SuggestionCategory,
  risk: SuggestionRisk,
  title: string,
  dirs: DirectoryHotspot[],
  reasoning: string,
): CleanupSuggestion {
  return {
    id: uid(),
    category,
    risk,
    title,
    description: `${dirs.length} director${dirs.length === 1 ? "y" : "ies"}, ${formatBytes(dirs.reduce((s, d) => s + d.size, 0))}`,
    paths: dirs.map((d) => d.path),
    totalSize: dirs.reduce((s, d) => s + d.size, 0),
    fileCount: dirs.reduce((s, d) => s + d.fileCount, 0),
    reasoning,
  };
}

function totalSize(files: ScanFileRecord[]): number {
  return files.reduce((sum, f) => sum + f.size, 0);
}

function matchesTempPath(path: string): boolean {
  const lower = path.toLowerCase();
  return lower.includes("\\temp\\") || lower.includes("/temp/")
    || lower.includes("\\tmp\\") || lower.includes("/tmp/");
}

function normalizePath(p: string): string {
  return p.replace(/\\/g, "/").toLowerCase();
}

const INDEX_SAMPLE_CAP = 250;

export async function analyzeCleanupFromIndex(
  rootPath: string,
  indexPath: string,
  settings: CleanupSettings,
): Promise<CleanupAnalysis> {
  if (!existsSync(indexPath)) {
    return {
      suggestions: [],
      totalReclaimableBytes: 0,
      analyzedAt: Date.now(),
      scanRootPath: rootPath,
    };
  }

  const now = Date.now();
  const oldThresholdMs = settings.oldFileThresholdDays * ONE_DAY_MS;
  const buckets = {
    temp: emptyBucket(),
    logs: emptyBucket(),
    caches: emptyBucket(),
    installers: emptyBucket(),
    downloads: emptyBucket(),
    media: emptyBucket(),
  };

  const gunzip = createGunzip();
  const source = createReadStream(indexPath);
  attachPipeErrorHandlers([source, gunzip]);
  source.pipe(gunzip);
  const rl = createInterface({ input: gunzip, crlfDelay: Infinity });

  try {
    for await (const line of rl) {
      if (!line) continue;
      let rec: { p?: string; s?: number; m?: number; t?: string; h?: number };
      try { rec = JSON.parse(line); } catch { continue; }
      if (!rec || typeof rec.p !== "string" || rec.t === "d" || typeof rec.s !== "number") continue;
      if (rec.h === 1) continue;
      const ext = Path.extname(rec.p).toLowerCase() || "(no ext)";
      const mtime = typeof rec.m === "number" ? rec.m : now;

      if (settings.autoDetectTempFiles) {
        if (TEMP_EXTENSIONS.has(ext) || matchesTempPath(rec.p)) addToBucket(buckets.temp, rec.p, rec.s);
        if (LOG_EXTENSIONS.has(ext)) addToBucket(buckets.logs, rec.p, rec.s);
      }
      if (settings.autoDetectCaches) {
        const dirName = Path.basename(Path.dirname(rec.p));
        if (BUILD_CACHE_DIRS.has(dirName)) addToBucket(buckets.caches, Path.dirname(rec.p), rec.s);
        const pathNorm = normalizePath(rec.p);
        if (BROWSER_CACHE_PATHS.some((bp) => pathNorm.includes(normalizePath(bp ?? "")))) {
          addToBucket(buckets.caches, rec.p, rec.s);
        }
      }
      if (settings.autoDetectOldDownloads && now - mtime > oldThresholdMs) {
        if (INSTALLER_EXTENSIONS.has(ext)) addToBucket(buckets.installers, rec.p, rec.s);
        else if (rec.p.toLowerCase().includes("download")) addToBucket(buckets.downloads, rec.p, rec.s);
      }
      if (LARGE_MEDIA_EXTENSIONS.has(ext) && rec.s > 100 * 1024 * 1024) {
        addToBucket(buckets.media, rec.p, rec.s);
      }
    }
  } catch { /* partial */ }
  finally {
    try { gunzip.destroy(); } catch { /* ok */ }
    try { source.destroy(); } catch { /* ok */ }
  }

  const suggestions: CleanupSuggestion[] = [];
  pushBucket(suggestions, buckets.temp, "temp-files", "safe", "Temporary Files",
    "Temporary files created by applications and the OS. Safe to remove.");
  pushBucket(suggestions, buckets.logs, "logs", "low", "Log Files",
    "Application and system log files. Usually safe to remove, but check if you need them for debugging.");
  pushBucket(suggestions, buckets.caches, "build-cache", "low", "Build & Package Caches",
    "Build outputs and package manager caches. Can be regenerated by rebuilding the project.");
  pushBucket(suggestions, buckets.installers, "installer-leftovers", "low",
    `Old Installers (>${settings.oldFileThresholdDays}d)`,
    "Installer files that haven't been modified in a long time. You've likely already installed these.");
  pushBucket(suggestions, buckets.downloads, "old-downloads", "medium",
    `Old Downloads (>${settings.oldFileThresholdDays}d)`,
    "Files in download folders that haven't been touched in a while. Review before deleting.");
  pushBucket(suggestions, buckets.media, "large-media", "medium", "Large Media & Disk Images",
    "Large video files and disk images. Check if you still need these — they're often the biggest space hogs.");

  suggestions.sort((a, b) => b.totalSize - a.totalSize);
  return {
    suggestions,
    totalReclaimableBytes: suggestions.reduce((sum, s) => sum + s.totalSize, 0),
    analyzedAt: now,
    scanRootPath: rootPath,
  };
}

function emptyBucket(): { paths: string[]; size: number; files: number } {
  return { paths: [], size: 0, files: 0 };
}

function addToBucket(bucket: { paths: string[]; size: number; files: number }, path: string, size: number): void {
  bucket.size += size;
  bucket.files += 1;
  if (bucket.paths.length < INDEX_SAMPLE_CAP && !bucket.paths.includes(path)) {
    bucket.paths.push(path);
  }
}

function pushBucket(
  suggestions: CleanupSuggestion[],
  bucket: { paths: string[]; size: number; files: number },
  category: SuggestionCategory,
  risk: SuggestionRisk,
  title: string,
  reasoning: string,
): void {
  if (bucket.size <= 0 || bucket.files <= 0) return;
  suggestions.push({
    id: uid(),
    category,
    risk,
    title,
    description: `${bucket.files.toLocaleString()} item${bucket.files === 1 ? "" : "s"}, ${formatBytes(bucket.size)}`,
    paths: bucket.paths,
    totalSize: bucket.size,
    fileCount: bucket.files,
    reasoning,
  });
}

function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  const units = ["B", "KB", "MB", "GB", "TB"];
  const exp = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  const val = bytes / 1024 ** exp;
  return `${val.toFixed(val >= 100 || exp === 0 ? 0 : 1)} ${units[exp]}`;
}
